=begin
#Apache Felix WebConsole

#Client for Apache Felix Web Console API. List bundles, configure services, etc.

OpenAPI spec version: 4.3.0
Contact: bryan.stopp@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ApacheFelix::BundleProps
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BundleProps' do
  before do
    # run before each test
    @instance = ApacheFelix::BundleProps.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BundleProps' do
    it 'should create an instact of BundleProps' do
      expect(@instance).to be_instance_of(ApacheFelix::BundleProps)
    end
  end
  describe 'test attribute "key"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

